WELL  'PRODUTOR 1'
PRODUCER 'PRODUTOR 1'
OPERATE  MIN  BHP  101.325  CONT 
**               rad      geofac    wfrac   skin
GEOMETRY  J  0.1397  0.37  1.0  0.0  
PERF      GEOA  'PRODUTOR 1'
** UBA              ff          Status  Connection  
  3 102 3           -  OPEN    FLOW-FROM  'SURFACE'
  3 102 4           -  OPEN    FLOW-FROM  1
  4 102 4           -  OPEN    FLOW-FROM  2
  4 102 3           -  OPEN    FLOW-FROM  3
  4 102 2           -  OPEN    FLOW-FROM  4
  3 102 2           -  OPEN    FLOW-FROM  5
  2 102 2           -  OPEN    FLOW-FROM  6
  2 102 3           -  OPEN    FLOW-FROM  7
  2 102 4           -  OPEN    FLOW-FROM  8
  2 102 5           -  OPEN    FLOW-FROM  9
  3 102 5           -  OPEN    FLOW-FROM  10
  4 102 5           -  OPEN    FLOW-FROM  11
  5 102 4           -  OPEN    FLOW-FROM  12
  5 102 3           -  OPEN    FLOW-FROM  13
  5 102 2           -  OPEN    FLOW-FROM  14
  4 102 1           -  OPEN    FLOW-FROM  15
  3 102 1           -  OPEN    FLOW-FROM  16
  2 102 1           -  OPEN    FLOW-FROM  17
  1 102 2           -  OPEN    FLOW-FROM  18
  1 102 3           -  OPEN    FLOW-FROM  19
  1 102 4           -  OPEN    FLOW-FROM  20
