WELL  'PRODUTOR 1'
PRODUCER 'PRODUTOR 1'
OPERATE  MIN  BHP  101.325  CONT 
**               rad      geofac    wfrac   skin
GEOMETRY  J  0.1397  0.37  1.0  0.0  
PERF      GEOA  'PRODUTOR 1'
** UBA              ff          Status  Connection  
  2 102 1           -  OPEN    FLOW-TO  'SURFACE'
  3 102 1           -  OPEN    FLOW-TO  1
  4 102 1           -  OPEN    FLOW-TO  2
  1 102 2           -  OPEN    FLOW-TO  3
  2 102 2           -  OPEN    FLOW-TO  4
  3 102 2           -  OPEN    FLOW-TO  5
  4 102 2           -  OPEN    FLOW-TO  6
  5 102 2           -  OPEN    FLOW-TO  7
  1 102 3           -  OPEN    FLOW-TO  8
  2 102 3           -  OPEN    FLOW-TO  9
  3 102 3           -  OPEN    FLOW-TO  10
  4 102 3           -  OPEN    FLOW-TO  11
  5 102 3           -  OPEN    FLOW-TO  12
  1 102 4           -  OPEN    FLOW-TO  13
  2 102 4           -  OPEN    FLOW-TO  14
  3 102 4           -  OPEN    FLOW-TO  15
  4 102 4           -  OPEN    FLOW-TO  16
  5 102 4           -  OPEN    FLOW-TO  17
  2 102 5           -  OPEN    FLOW-TO  18
  3 102 5           -  OPEN    FLOW-TO  19
  4 102 5           -  OPEN    FLOW-TO  20
