WELL  'INJE 1'
INJECTOR MOBWEIGHT 'INJE 1'
INCOMP  WATER
OPERATE  MAX  STW  0.005555555555555556 CONT
OPERATE  MAX  BHP  1000  CONT
**               rad      geofac    wfrac   skin
*GEOMETRY  *J    1.125    0.37       1.00    0.0  
PERF        WI  'INJE 1'
** UBA             wi          Status  Connection  
  1 1 1           1.0  OPEN    FLOW-FROM  'SURFACE'
  1 1 2           1.0  OPEN    FLOW-FROM  1
  1 1 3           1.0  OPEN    FLOW-FROM  2
  1 1 4           1.0  OPEN    FLOW-FROM  3
  1 1 5           1.0  OPEN    FLOW-FROM  4
  1 1 6           1.0  OPEN    FLOW-FROM  5
  1 1 7           1.0  OPEN    FLOW-FROM  6
  1 1 8           1.0  OPEN    FLOW-FROM  7
  1 1 9           1.0  OPEN    FLOW-FROM  8
  1 1 10           1.0  OPEN    FLOW-FROM  9
  1 1 11           1.0  OPEN    FLOW-FROM  10
  1 1 12           1.0  OPEN    FLOW-FROM  11
  1 1 13           1.0  OPEN    FLOW-FROM  12
  1 1 14           1.0  OPEN    FLOW-FROM  13
  1 1 15           1.0  OPEN    FLOW-FROM  14
  1 1 16           1.0  OPEN    FLOW-FROM  15
  1 1 17           1.0  OPEN    FLOW-FROM  16


WELL  'INJE 2'
INJECTOR MOBWEIGHT 'INJE 2'
INCOMP  WATER
OPERATE  MAX  STW  0.01 CONT
OPERATE  MAX  BHP  1000  CONT
**               rad      geofac    wfrac   skin
*GEOMETRY  *J    1.125    0.37       1.00    0.0  
PERF        WI  'INJE 2'
** UBA             wi          Status  Connection  
  2 1 1           1.0  OPEN    FLOW-FROM  'SURFACE'
  2 1 2           1.0  OPEN    FLOW-FROM  1
  2 1 3           1.0  OPEN    FLOW-FROM  2
  2 1 4           1.0  OPEN    FLOW-FROM  3
  2 1 5           1.0  OPEN    FLOW-FROM  4
  2 1 6           1.0  OPEN    FLOW-FROM  5
  2 1 7           1.0  OPEN    FLOW-FROM  6
  2 1 8           1.0  OPEN    FLOW-FROM  7
  2 1 9           1.0  OPEN    FLOW-FROM  8
  2 1 10           1.0  OPEN    FLOW-FROM  9
  2 1 11           1.0  OPEN    FLOW-FROM  10
  2 1 12           1.0  OPEN    FLOW-FROM  11
  2 1 13           1.0  OPEN    FLOW-FROM  12
  2 1 14           1.0  OPEN    FLOW-FROM  13
  2 1 15           1.0  OPEN    FLOW-FROM  14
  2 1 16           1.0  OPEN    FLOW-FROM  15
  2 1 17           1.0  OPEN    FLOW-FROM  16


WELL  'INJE 3'
INJECTOR MOBWEIGHT 'INJE 3'
INCOMP  WATER
OPERATE  MAX  STW  0.014444444444444444 CONT
OPERATE  MAX  BHP  1000  CONT
**               rad      geofac    wfrac   skin
*GEOMETRY  *J    1.125    0.37       1.00    0.0  
PERF        WI  'INJE 3'
** UBA             wi          Status  Connection  
  3 1 1           1.0  OPEN    FLOW-FROM  'SURFACE'
  3 1 2           1.0  OPEN    FLOW-FROM  1
  3 1 3           1.0  OPEN    FLOW-FROM  2
  3 1 4           1.0  OPEN    FLOW-FROM  3
  3 1 5           1.0  OPEN    FLOW-FROM  4
  3 1 6           1.0  OPEN    FLOW-FROM  5
  3 1 7           1.0  OPEN    FLOW-FROM  6
  3 1 8           1.0  OPEN    FLOW-FROM  7
  3 1 9           1.0  OPEN    FLOW-FROM  8
  3 1 10           1.0  OPEN    FLOW-FROM  9
  3 1 11           1.0  OPEN    FLOW-FROM  10
  3 1 12           1.0  OPEN    FLOW-FROM  11
  3 1 13           1.0  OPEN    FLOW-FROM  12
  3 1 14           1.0  OPEN    FLOW-FROM  13
  3 1 15           1.0  OPEN    FLOW-FROM  14
  3 1 16           1.0  OPEN    FLOW-FROM  15
  3 1 17           1.0  OPEN    FLOW-FROM  16


WELL  'INJE 4'
INJECTOR MOBWEIGHT 'INJE 4'
INCOMP  WATER
OPERATE  MAX  STW  0.014444444444444444 CONT
OPERATE  MAX  BHP  1000  CONT
**               rad      geofac    wfrac   skin
*GEOMETRY  *J    1.125    0.37       1.00    0.0  
PERF        WI  'INJE 4'
** UBA             wi          Status  Connection  
  4 1 1           1.0  OPEN    FLOW-FROM  'SURFACE'
  4 1 2           1.0  OPEN    FLOW-FROM  1
  4 1 3           1.0  OPEN    FLOW-FROM  2
  4 1 4           1.0  OPEN    FLOW-FROM  3
  4 1 5           1.0  OPEN    FLOW-FROM  4
  4 1 6           1.0  OPEN    FLOW-FROM  5
  4 1 7           1.0  OPEN    FLOW-FROM  6
  4 1 8           1.0  OPEN    FLOW-FROM  7
  4 1 9           1.0  OPEN    FLOW-FROM  8
  4 1 10           1.0  OPEN    FLOW-FROM  9
  4 1 11           1.0  OPEN    FLOW-FROM  10
  4 1 12           1.0  OPEN    FLOW-FROM  11
  4 1 13           1.0  OPEN    FLOW-FROM  12
  4 1 14           1.0  OPEN    FLOW-FROM  13
  4 1 15           1.0  OPEN    FLOW-FROM  14
  4 1 16           1.0  OPEN    FLOW-FROM  15
  4 1 17           1.0  OPEN    FLOW-FROM  16


WELL  'INJE 5'
INJECTOR MOBWEIGHT 'INJE 5'
INCOMP  WATER
OPERATE  MAX  STW  0.016666666666666666 CONT
OPERATE  MAX  BHP  1000  CONT
**               rad      geofac    wfrac   skin
*GEOMETRY  *J    1.125    0.37       1.00    0.0  
PERF        WI  'INJE 5'
** UBA             wi          Status  Connection  
  5 1 1           1.0  OPEN    FLOW-FROM  'SURFACE'
  5 1 2           1.0  OPEN    FLOW-FROM  1
  5 1 3           1.0  OPEN    FLOW-FROM  2
  5 1 4           1.0  OPEN    FLOW-FROM  3
  5 1 5           1.0  OPEN    FLOW-FROM  4
  5 1 6           1.0  OPEN    FLOW-FROM  5
  5 1 7           1.0  OPEN    FLOW-FROM  6
  5 1 8           1.0  OPEN    FLOW-FROM  7
  5 1 9           1.0  OPEN    FLOW-FROM  8
  5 1 10           1.0  OPEN    FLOW-FROM  9
  5 1 11           1.0  OPEN    FLOW-FROM  10
  5 1 12           1.0  OPEN    FLOW-FROM  11
  5 1 13           1.0  OPEN    FLOW-FROM  12
  5 1 14           1.0  OPEN    FLOW-FROM  13
  5 1 15           1.0  OPEN    FLOW-FROM  14
  5 1 16           1.0  OPEN    FLOW-FROM  15
  5 1 17           1.0  OPEN    FLOW-FROM  16


WELL  'INJE 6'
INJECTOR MOBWEIGHT 'INJE 6'
INCOMP  WATER
OPERATE  MAX  STW  0.016666666666666666 CONT
OPERATE  MAX  BHP  1000  CONT
**               rad      geofac    wfrac   skin
*GEOMETRY  *J    1.125    0.37       1.00    0.0  
PERF        WI  'INJE 6'
** UBA             wi          Status  Connection  
  6 1 1           1.0  OPEN    FLOW-FROM  'SURFACE'
  6 1 2           1.0  OPEN    FLOW-FROM  1
  6 1 3           1.0  OPEN    FLOW-FROM  2
  6 1 4           1.0  OPEN    FLOW-FROM  3
  6 1 5           1.0  OPEN    FLOW-FROM  4
  6 1 6           1.0  OPEN    FLOW-FROM  5
  6 1 7           1.0  OPEN    FLOW-FROM  6
  6 1 8           1.0  OPEN    FLOW-FROM  7
  6 1 9           1.0  OPEN    FLOW-FROM  8
  6 1 10           1.0  OPEN    FLOW-FROM  9
  6 1 11           1.0  OPEN    FLOW-FROM  10
  6 1 12           1.0  OPEN    FLOW-FROM  11
  6 1 13           1.0  OPEN    FLOW-FROM  12
  6 1 14           1.0  OPEN    FLOW-FROM  13
  6 1 15           1.0  OPEN    FLOW-FROM  14
  6 1 16           1.0  OPEN    FLOW-FROM  15
  6 1 17           1.0  OPEN    FLOW-FROM  16


WELL  'INJE 7'
INJECTOR MOBWEIGHT 'INJE 7'
INCOMP  WATER
OPERATE  MAX  STW  0.01888888888888889 CONT
OPERATE  MAX  BHP  1000  CONT
**               rad      geofac    wfrac   skin
*GEOMETRY  *J    1.125    0.37       1.00    0.0  
PERF        WI  'INJE 7'
** UBA             wi          Status  Connection  
  7 1 1           1.0  OPEN    FLOW-FROM  'SURFACE'
  7 1 2           1.0  OPEN    FLOW-FROM  1
  7 1 3           1.0  OPEN    FLOW-FROM  2
  7 1 4           1.0  OPEN    FLOW-FROM  3
  7 1 5           1.0  OPEN    FLOW-FROM  4
  7 1 6           1.0  OPEN    FLOW-FROM  5
  7 1 7           1.0  OPEN    FLOW-FROM  6
  7 1 8           1.0  OPEN    FLOW-FROM  7
  7 1 9           1.0  OPEN    FLOW-FROM  8
  7 1 10           1.0  OPEN    FLOW-FROM  9
  7 1 11           1.0  OPEN    FLOW-FROM  10
  7 1 12           1.0  OPEN    FLOW-FROM  11
  7 1 13           1.0  OPEN    FLOW-FROM  12
  7 1 14           1.0  OPEN    FLOW-FROM  13
  7 1 15           1.0  OPEN    FLOW-FROM  14
  7 1 16           1.0  OPEN    FLOW-FROM  15
  7 1 17           1.0  OPEN    FLOW-FROM  16


WELL  'INJE 8'
INJECTOR MOBWEIGHT 'INJE 8'
INCOMP  WATER
OPERATE  MAX  STW  0.01888888888888889 CONT
OPERATE  MAX  BHP  1000  CONT
**               rad      geofac    wfrac   skin
*GEOMETRY  *J    1.125    0.37       1.00    0.0  
PERF        WI  'INJE 8'
** UBA             wi          Status  Connection  
  8 1 1           1.0  OPEN    FLOW-FROM  'SURFACE'
  8 1 2           1.0  OPEN    FLOW-FROM  1
  8 1 3           1.0  OPEN    FLOW-FROM  2
  8 1 4           1.0  OPEN    FLOW-FROM  3
  8 1 5           1.0  OPEN    FLOW-FROM  4
  8 1 6           1.0  OPEN    FLOW-FROM  5
  8 1 7           1.0  OPEN    FLOW-FROM  6
  8 1 8           1.0  OPEN    FLOW-FROM  7
  8 1 9           1.0  OPEN    FLOW-FROM  8
  8 1 10           1.0  OPEN    FLOW-FROM  9
  8 1 11           1.0  OPEN    FLOW-FROM  10
  8 1 12           1.0  OPEN    FLOW-FROM  11
  8 1 13           1.0  OPEN    FLOW-FROM  12
  8 1 14           1.0  OPEN    FLOW-FROM  13
  8 1 15           1.0  OPEN    FLOW-FROM  14
  8 1 16           1.0  OPEN    FLOW-FROM  15
  8 1 17           1.0  OPEN    FLOW-FROM  16


WELL  'INJE 9'
INJECTOR MOBWEIGHT 'INJE 9'
INCOMP  WATER
OPERATE  MAX  STW  0.01888888888888889 CONT
OPERATE  MAX  BHP  1000  CONT
**               rad      geofac    wfrac   skin
*GEOMETRY  *J    1.125    0.37       1.00    0.0  
PERF        WI  'INJE 9'
** UBA             wi          Status  Connection  
  9 1 1           1.0  OPEN    FLOW-FROM  'SURFACE'
  9 1 2           1.0  OPEN    FLOW-FROM  1
  9 1 3           1.0  OPEN    FLOW-FROM  2
  9 1 4           1.0  OPEN    FLOW-FROM  3
  9 1 5           1.0  OPEN    FLOW-FROM  4
  9 1 6           1.0  OPEN    FLOW-FROM  5
  9 1 7           1.0  OPEN    FLOW-FROM  6
  9 1 8           1.0  OPEN    FLOW-FROM  7
  9 1 9           1.0  OPEN    FLOW-FROM  8
  9 1 10           1.0  OPEN    FLOW-FROM  9
  9 1 11           1.0  OPEN    FLOW-FROM  10
  9 1 12           1.0  OPEN    FLOW-FROM  11
  9 1 13           1.0  OPEN    FLOW-FROM  12
  9 1 14           1.0  OPEN    FLOW-FROM  13
  9 1 15           1.0  OPEN    FLOW-FROM  14
  9 1 16           1.0  OPEN    FLOW-FROM  15
  9 1 17           1.0  OPEN    FLOW-FROM  16


WELL  'INJE 10'
INJECTOR MOBWEIGHT 'INJE 10'
INCOMP  WATER
OPERATE  MAX  STW  0.01888888888888889 CONT
OPERATE  MAX  BHP  1000  CONT
**               rad      geofac    wfrac   skin
*GEOMETRY  *J    1.125    0.37       1.00    0.0  
PERF        WI  'INJE 10'
** UBA             wi          Status  Connection  
  10 1 1           1.0  OPEN    FLOW-FROM  'SURFACE'
  10 1 2           1.0  OPEN    FLOW-FROM  1
  10 1 3           1.0  OPEN    FLOW-FROM  2
  10 1 4           1.0  OPEN    FLOW-FROM  3
  10 1 5           1.0  OPEN    FLOW-FROM  4
  10 1 6           1.0  OPEN    FLOW-FROM  5
  10 1 7           1.0  OPEN    FLOW-FROM  6
  10 1 8           1.0  OPEN    FLOW-FROM  7
  10 1 9           1.0  OPEN    FLOW-FROM  8
  10 1 10           1.0  OPEN    FLOW-FROM  9
  10 1 11           1.0  OPEN    FLOW-FROM  10
  10 1 12           1.0  OPEN    FLOW-FROM  11
  10 1 13           1.0  OPEN    FLOW-FROM  12
  10 1 14           1.0  OPEN    FLOW-FROM  13
  10 1 15           1.0  OPEN    FLOW-FROM  14
  10 1 16           1.0  OPEN    FLOW-FROM  15
  10 1 17           1.0  OPEN    FLOW-FROM  16


WELL  'INJE 11'
INJECTOR MOBWEIGHT 'INJE 11'
INCOMP  WATER
OPERATE  MAX  STW  0.01888888888888889 CONT
OPERATE  MAX  BHP  1000  CONT
**               rad      geofac    wfrac   skin
*GEOMETRY  *J    1.125    0.37       1.00    0.0  
PERF        WI  'INJE 11'
** UBA             wi          Status  Connection  
  11 1 1           1.0  OPEN    FLOW-FROM  'SURFACE'
  11 1 2           1.0  OPEN    FLOW-FROM  1
  11 1 3           1.0  OPEN    FLOW-FROM  2
  11 1 4           1.0  OPEN    FLOW-FROM  3
  11 1 5           1.0  OPEN    FLOW-FROM  4
  11 1 6           1.0  OPEN    FLOW-FROM  5
  11 1 7           1.0  OPEN    FLOW-FROM  6
  11 1 8           1.0  OPEN    FLOW-FROM  7
  11 1 9           1.0  OPEN    FLOW-FROM  8
  11 1 10           1.0  OPEN    FLOW-FROM  9
  11 1 11           1.0  OPEN    FLOW-FROM  10
  11 1 12           1.0  OPEN    FLOW-FROM  11
  11 1 13           1.0  OPEN    FLOW-FROM  12
  11 1 14           1.0  OPEN    FLOW-FROM  13
  11 1 15           1.0  OPEN    FLOW-FROM  14
  11 1 16           1.0  OPEN    FLOW-FROM  15
  11 1 17           1.0  OPEN    FLOW-FROM  16


WELL  'INJE 12'
INJECTOR MOBWEIGHT 'INJE 12'
INCOMP  WATER
OPERATE  MAX  STW  0.016666666666666666 CONT
OPERATE  MAX  BHP  1000  CONT
**               rad      geofac    wfrac   skin
*GEOMETRY  *J    1.125    0.37       1.00    0.0  
PERF        WI  'INJE 12'
** UBA             wi          Status  Connection  
  12 1 1           1.0  OPEN    FLOW-FROM  'SURFACE'
  12 1 2           1.0  OPEN    FLOW-FROM  1
  12 1 3           1.0  OPEN    FLOW-FROM  2
  12 1 4           1.0  OPEN    FLOW-FROM  3
  12 1 5           1.0  OPEN    FLOW-FROM  4
  12 1 6           1.0  OPEN    FLOW-FROM  5
  12 1 7           1.0  OPEN    FLOW-FROM  6
  12 1 8           1.0  OPEN    FLOW-FROM  7
  12 1 9           1.0  OPEN    FLOW-FROM  8
  12 1 10           1.0  OPEN    FLOW-FROM  9
  12 1 11           1.0  OPEN    FLOW-FROM  10
  12 1 12           1.0  OPEN    FLOW-FROM  11
  12 1 13           1.0  OPEN    FLOW-FROM  12
  12 1 14           1.0  OPEN    FLOW-FROM  13
  12 1 15           1.0  OPEN    FLOW-FROM  14
  12 1 16           1.0  OPEN    FLOW-FROM  15
  12 1 17           1.0  OPEN    FLOW-FROM  16


WELL  'INJE 13'
INJECTOR MOBWEIGHT 'INJE 13'
INCOMP  WATER
OPERATE  MAX  STW  0.016666666666666666 CONT
OPERATE  MAX  BHP  1000  CONT
**               rad      geofac    wfrac   skin
*GEOMETRY  *J    1.125    0.37       1.00    0.0  
PERF        WI  'INJE 13'
** UBA             wi          Status  Connection  
  13 1 1           1.0  OPEN    FLOW-FROM  'SURFACE'
  13 1 2           1.0  OPEN    FLOW-FROM  1
  13 1 3           1.0  OPEN    FLOW-FROM  2
  13 1 4           1.0  OPEN    FLOW-FROM  3
  13 1 5           1.0  OPEN    FLOW-FROM  4
  13 1 6           1.0  OPEN    FLOW-FROM  5
  13 1 7           1.0  OPEN    FLOW-FROM  6
  13 1 8           1.0  OPEN    FLOW-FROM  7
  13 1 9           1.0  OPEN    FLOW-FROM  8
  13 1 10           1.0  OPEN    FLOW-FROM  9
  13 1 11           1.0  OPEN    FLOW-FROM  10
  13 1 12           1.0  OPEN    FLOW-FROM  11
  13 1 13           1.0  OPEN    FLOW-FROM  12
  13 1 14           1.0  OPEN    FLOW-FROM  13
  13 1 15           1.0  OPEN    FLOW-FROM  14
  13 1 16           1.0  OPEN    FLOW-FROM  15
  13 1 17           1.0  OPEN    FLOW-FROM  16


WELL  'INJE 14'
INJECTOR MOBWEIGHT 'INJE 14'
INCOMP  WATER
OPERATE  MAX  STW  0.014444444444444444 CONT
OPERATE  MAX  BHP  1000  CONT
**               rad      geofac    wfrac   skin
*GEOMETRY  *J    1.125    0.37       1.00    0.0  
PERF        WI  'INJE 14'
** UBA             wi          Status  Connection  
  14 1 1           1.0  OPEN    FLOW-FROM  'SURFACE'
  14 1 2           1.0  OPEN    FLOW-FROM  1
  14 1 3           1.0  OPEN    FLOW-FROM  2
  14 1 4           1.0  OPEN    FLOW-FROM  3
  14 1 5           1.0  OPEN    FLOW-FROM  4
  14 1 6           1.0  OPEN    FLOW-FROM  5
  14 1 7           1.0  OPEN    FLOW-FROM  6
  14 1 8           1.0  OPEN    FLOW-FROM  7
  14 1 9           1.0  OPEN    FLOW-FROM  8
  14 1 10           1.0  OPEN    FLOW-FROM  9
  14 1 11           1.0  OPEN    FLOW-FROM  10
  14 1 12           1.0  OPEN    FLOW-FROM  11
  14 1 13           1.0  OPEN    FLOW-FROM  12
  14 1 14           1.0  OPEN    FLOW-FROM  13
  14 1 15           1.0  OPEN    FLOW-FROM  14
  14 1 16           1.0  OPEN    FLOW-FROM  15
  14 1 17           1.0  OPEN    FLOW-FROM  16


WELL  'INJE 15'
INJECTOR MOBWEIGHT 'INJE 15'
INCOMP  WATER
OPERATE  MAX  STW  0.014444444444444444 CONT
OPERATE  MAX  BHP  1000  CONT
**               rad      geofac    wfrac   skin
*GEOMETRY  *J    1.125    0.37       1.00    0.0  
PERF        WI  'INJE 15'
** UBA             wi          Status  Connection  
  15 1 1           1.0  OPEN    FLOW-FROM  'SURFACE'
  15 1 2           1.0  OPEN    FLOW-FROM  1
  15 1 3           1.0  OPEN    FLOW-FROM  2
  15 1 4           1.0  OPEN    FLOW-FROM  3
  15 1 5           1.0  OPEN    FLOW-FROM  4
  15 1 6           1.0  OPEN    FLOW-FROM  5
  15 1 7           1.0  OPEN    FLOW-FROM  6
  15 1 8           1.0  OPEN    FLOW-FROM  7
  15 1 9           1.0  OPEN    FLOW-FROM  8
  15 1 10           1.0  OPEN    FLOW-FROM  9
  15 1 11           1.0  OPEN    FLOW-FROM  10
  15 1 12           1.0  OPEN    FLOW-FROM  11
  15 1 13           1.0  OPEN    FLOW-FROM  12
  15 1 14           1.0  OPEN    FLOW-FROM  13
  15 1 15           1.0  OPEN    FLOW-FROM  14
  15 1 16           1.0  OPEN    FLOW-FROM  15
  15 1 17           1.0  OPEN    FLOW-FROM  16


WELL  'INJE 16'
INJECTOR MOBWEIGHT 'INJE 16'
INCOMP  WATER
OPERATE  MAX  STW  0.01 CONT
OPERATE  MAX  BHP  1000  CONT
**               rad      geofac    wfrac   skin
*GEOMETRY  *J    1.125    0.37       1.00    0.0  
PERF        WI  'INJE 16'
** UBA             wi          Status  Connection  
  16 1 1           1.0  OPEN    FLOW-FROM  'SURFACE'
  16 1 2           1.0  OPEN    FLOW-FROM  1
  16 1 3           1.0  OPEN    FLOW-FROM  2
  16 1 4           1.0  OPEN    FLOW-FROM  3
  16 1 5           1.0  OPEN    FLOW-FROM  4
  16 1 6           1.0  OPEN    FLOW-FROM  5
  16 1 7           1.0  OPEN    FLOW-FROM  6
  16 1 8           1.0  OPEN    FLOW-FROM  7
  16 1 9           1.0  OPEN    FLOW-FROM  8
  16 1 10           1.0  OPEN    FLOW-FROM  9
  16 1 11           1.0  OPEN    FLOW-FROM  10
  16 1 12           1.0  OPEN    FLOW-FROM  11
  16 1 13           1.0  OPEN    FLOW-FROM  12
  16 1 14           1.0  OPEN    FLOW-FROM  13
  16 1 15           1.0  OPEN    FLOW-FROM  14
  16 1 16           1.0  OPEN    FLOW-FROM  15
  16 1 17           1.0  OPEN    FLOW-FROM  16


WELL  'INJE 17'
INJECTOR MOBWEIGHT 'INJE 17'
INCOMP  WATER
OPERATE  MAX  STW  0.005555555555555556 CONT
OPERATE  MAX  BHP  1000  CONT
**               rad      geofac    wfrac   skin
*GEOMETRY  *J    1.125    0.37       1.00    0.0  
PERF        WI  'INJE 17'
** UBA             wi          Status  Connection  
  17 1 1           1.0  OPEN    FLOW-FROM  'SURFACE'
  17 1 2           1.0  OPEN    FLOW-FROM  1
  17 1 3           1.0  OPEN    FLOW-FROM  2
  17 1 4           1.0  OPEN    FLOW-FROM  3
  17 1 5           1.0  OPEN    FLOW-FROM  4
  17 1 6           1.0  OPEN    FLOW-FROM  5
  17 1 7           1.0  OPEN    FLOW-FROM  6
  17 1 8           1.0  OPEN    FLOW-FROM  7
  17 1 9           1.0  OPEN    FLOW-FROM  8
  17 1 10           1.0  OPEN    FLOW-FROM  9
  17 1 11           1.0  OPEN    FLOW-FROM  10
  17 1 12           1.0  OPEN    FLOW-FROM  11
  17 1 13           1.0  OPEN    FLOW-FROM  12
  17 1 14           1.0  OPEN    FLOW-FROM  13
  17 1 15           1.0  OPEN    FLOW-FROM  14
  17 1 16           1.0  OPEN    FLOW-FROM  15
  17 1 17           1.0  OPEN    FLOW-FROM  16









  *TIME 600.0
DTWELL 0.00166667
  *ALTER 'INJE 1'
  0.011111111111111112
  *ALTER 'INJE 2'
  0.02
  *ALTER 'INJE 3'
  0.028888888888888888
  *ALTER 'INJE 4'
  0.028888888888888888
  *ALTER 'INJE 5'
  0.03333333333333333
  *ALTER 'INJE 6'
  0.03333333333333333
  *ALTER 'INJE 7'
  0.03777777777777778
  *ALTER 'INJE 8'
  0.03777777777777778
  *ALTER 'INJE 9'
  0.03777777777777778
  *ALTER 'INJE 10'
  0.03777777777777778
  *ALTER 'INJE 11'
  0.03777777777777778
  *ALTER 'INJE 12'
  0.03333333333333333
  *ALTER 'INJE 13'
  0.03333333333333333
  *ALTER 'INJE 14'
  0.028888888888888888
  *ALTER 'INJE 15'
  0.028888888888888888
  *ALTER 'INJE 16'
  0.02
  *ALTER 'INJE 17'
  0.011111111111111112

  *TIME 1200.0
DTWELL 0.00166667
  *ALTER 'INJE 1'
  0.016666666666666666
  *ALTER 'INJE 2'
  0.030000000000000002
  *ALTER 'INJE 3'
  0.043333333333333335
  *ALTER 'INJE 4'
  0.043333333333333335
  *ALTER 'INJE 5'
  0.05
  *ALTER 'INJE 6'
  0.05
  *ALTER 'INJE 7'
  0.05666666666666667
  *ALTER 'INJE 8'
  0.05666666666666667
  *ALTER 'INJE 9'
  0.05666666666666667
  *ALTER 'INJE 10'
  0.05666666666666667
  *ALTER 'INJE 11'
  0.05666666666666667
  *ALTER 'INJE 12'
  0.05
  *ALTER 'INJE 13'
  0.05
  *ALTER 'INJE 14'
  0.043333333333333335
  *ALTER 'INJE 15'
  0.043333333333333335
  *ALTER 'INJE 16'
  0.030000000000000002
  *ALTER 'INJE 17'
  0.016666666666666666

  *TIME 2160.0
DTWELL 0.00166667
  *ALTER 'INJE 1'
  0.022222222222222223
  *ALTER 'INJE 2'
  0.04
  *ALTER 'INJE 3'
  0.057777777777777775
  *ALTER 'INJE 4'
  0.057777777777777775
  *ALTER 'INJE 5'
  0.06666666666666667
  *ALTER 'INJE 6'
  0.06666666666666667
  *ALTER 'INJE 7'
  0.07555555555555556
  *ALTER 'INJE 8'
  0.07555555555555556
  *ALTER 'INJE 9'
  0.07555555555555556
  *ALTER 'INJE 10'
  0.07555555555555556
  *ALTER 'INJE 11'
  0.07555555555555556
  *ALTER 'INJE 12'
  0.06666666666666667
  *ALTER 'INJE 13'
  0.06666666666666667
  *ALTER 'INJE 14'
  0.057777777777777775
  *ALTER 'INJE 15'
  0.057777777777777775
  *ALTER 'INJE 16'
  0.04
  *ALTER 'INJE 17'
  0.022222222222222223

  *TIME 3600.0
DTWELL 0.00166667
  *ALTER 'INJE 1'
  0.044444444444444446
  *ALTER 'INJE 2'
  0.08
  *ALTER 'INJE 3'
  0.11555555555555555
  *ALTER 'INJE 4'
  0.11555555555555555
  *ALTER 'INJE 5'
  0.13333333333333333
  *ALTER 'INJE 6'
  0.13333333333333333
  *ALTER 'INJE 7'
  0.1511111111111111
  *ALTER 'INJE 8'
  0.1511111111111111
  *ALTER 'INJE 9'
  0.1511111111111111
  *ALTER 'INJE 10'
  0.1511111111111111
  *ALTER 'INJE 11'
  0.1511111111111111
  *ALTER 'INJE 12'
  0.13333333333333333
  *ALTER 'INJE 13'
  0.13333333333333333
  *ALTER 'INJE 14'
  0.11555555555555555
  *ALTER 'INJE 15'
  0.11555555555555555
  *ALTER 'INJE 16'
  0.08
  *ALTER 'INJE 17'
  0.044444444444444446

  *TIME 5040.0
DTWELL 0.00166667
  *ALTER 'INJE 1'
  0.08888888888888889
  *ALTER 'INJE 2'
  0.16
  *ALTER 'INJE 3'
  0.2311111111111111
  *ALTER 'INJE 4'
  0.2311111111111111
  *ALTER 'INJE 5'
  0.26666666666666666
  *ALTER 'INJE 6'
  0.26666666666666666
  *ALTER 'INJE 7'
  0.3022222222222222
  *ALTER 'INJE 8'
  0.3022222222222222
  *ALTER 'INJE 9'
  0.3022222222222222
  *ALTER 'INJE 10'
  0.3022222222222222
  *ALTER 'INJE 11'
  0.3022222222222222
  *ALTER 'INJE 12'
  0.26666666666666666
  *ALTER 'INJE 13'
  0.26666666666666666
  *ALTER 'INJE 14'
  0.2311111111111111
  *ALTER 'INJE 15'
  0.2311111111111111
  *ALTER 'INJE 16'
  0.16
  *ALTER 'INJE 17'
  0.08888888888888889

  *TIME 7920.0
