WELL  'PRODUTOR 1'
PRODUCER 'PRODUTOR 1'
OPERATE  MIN  BHP  101.325  CONT 
**               rad      geofac    wfrac   skin
GEOMETRY  J  0.1397  0.37  1.0  0.0  
PERF      GEOA  'PRODUTOR 1'
** UBA              ff          Status  Connection  
  1 352 1           -  OPEN    FLOW-TO  'SURFACE'
  1 352 2           -  OPEN    FLOW-TO  1
  1 352 3           -  OPEN    FLOW-TO  2
  1 352 4           -  OPEN    FLOW-TO  3
  1 352 5           -  OPEN    FLOW-TO  4
  1 352 6           -  OPEN    FLOW-TO  5
  1 352 7           -  OPEN    FLOW-TO  6
  1 352 8           -  OPEN    FLOW-TO  7
  1 352 9           -  OPEN    FLOW-TO  8
  1 352 10           -  OPEN    FLOW-TO  9
  1 352 11           -  OPEN    FLOW-TO  10
  1 352 12           -  OPEN    FLOW-TO  11
  1 352 13           -  OPEN    FLOW-TO  12
  1 352 14           -  OPEN    FLOW-TO  13
  1 352 15           -  OPEN    FLOW-TO  14
  1 352 16           -  OPEN    FLOW-TO  15
  1 352 17           -  OPEN    FLOW-TO  16


WELL  'PRODUTOR 2'
PRODUCER 'PRODUTOR 2'
OPERATE  MIN  BHP  101.325  CONT 
**               rad      geofac    wfrac   skin
GEOMETRY  J  0.1397  0.37  1.0  0.0  
PERF      GEOA  'PRODUTOR 2'
** UBA              ff          Status  Connection  
  2 352 1           -  OPEN    FLOW-TO  'SURFACE'
  2 352 2           -  OPEN    FLOW-TO  1
  2 352 3           -  OPEN    FLOW-TO  2
  2 352 4           -  OPEN    FLOW-TO  3
  2 352 5           -  OPEN    FLOW-TO  4
  2 352 6           -  OPEN    FLOW-TO  5
  2 352 7           -  OPEN    FLOW-TO  6
  2 352 8           -  OPEN    FLOW-TO  7
  2 352 9           -  OPEN    FLOW-TO  8
  2 352 10           -  OPEN    FLOW-TO  9
  2 352 11           -  OPEN    FLOW-TO  10
  2 352 12           -  OPEN    FLOW-TO  11
  2 352 13           -  OPEN    FLOW-TO  12
  2 352 14           -  OPEN    FLOW-TO  13
  2 352 15           -  OPEN    FLOW-TO  14
  2 352 16           -  OPEN    FLOW-TO  15
  2 352 17           -  OPEN    FLOW-TO  16


WELL  'PRODUTOR 3'
PRODUCER 'PRODUTOR 3'
OPERATE  MIN  BHP  101.325  CONT 
**               rad      geofac    wfrac   skin
GEOMETRY  J  0.1397  0.37  1.0  0.0  
PERF      GEOA  'PRODUTOR 3'
** UBA              ff          Status  Connection  
  3 352 1           -  OPEN    FLOW-TO  'SURFACE'
  3 352 2           -  OPEN    FLOW-TO  1
  3 352 3           -  OPEN    FLOW-TO  2
  3 352 4           -  OPEN    FLOW-TO  3
  3 352 5           -  OPEN    FLOW-TO  4
  3 352 6           -  OPEN    FLOW-TO  5
  3 352 7           -  OPEN    FLOW-TO  6
  3 352 8           -  OPEN    FLOW-TO  7
  3 352 9           -  OPEN    FLOW-TO  8
  3 352 10           -  OPEN    FLOW-TO  9
  3 352 11           -  OPEN    FLOW-TO  10
  3 352 12           -  OPEN    FLOW-TO  11
  3 352 13           -  OPEN    FLOW-TO  12
  3 352 14           -  OPEN    FLOW-TO  13
  3 352 15           -  OPEN    FLOW-TO  14
  3 352 16           -  OPEN    FLOW-TO  15
  3 352 17           -  OPEN    FLOW-TO  16


WELL  'PRODUTOR 4'
PRODUCER 'PRODUTOR 4'
OPERATE  MIN  BHP  101.325  CONT 
**               rad      geofac    wfrac   skin
GEOMETRY  J  0.1397  0.37  1.0  0.0  
PERF      GEOA  'PRODUTOR 4'
** UBA              ff          Status  Connection  
  4 352 1           -  OPEN    FLOW-TO  'SURFACE'
  4 352 2           -  OPEN    FLOW-TO  1
  4 352 3           -  OPEN    FLOW-TO  2
  4 352 4           -  OPEN    FLOW-TO  3
  4 352 5           -  OPEN    FLOW-TO  4
  4 352 6           -  OPEN    FLOW-TO  5
  4 352 7           -  OPEN    FLOW-TO  6
  4 352 8           -  OPEN    FLOW-TO  7
  4 352 9           -  OPEN    FLOW-TO  8
  4 352 10           -  OPEN    FLOW-TO  9
  4 352 11           -  OPEN    FLOW-TO  10
  4 352 12           -  OPEN    FLOW-TO  11
  4 352 13           -  OPEN    FLOW-TO  12
  4 352 14           -  OPEN    FLOW-TO  13
  4 352 15           -  OPEN    FLOW-TO  14
  4 352 16           -  OPEN    FLOW-TO  15
  4 352 17           -  OPEN    FLOW-TO  16


WELL  'PRODUTOR 5'
PRODUCER 'PRODUTOR 5'
OPERATE  MIN  BHP  101.325  CONT 
**               rad      geofac    wfrac   skin
GEOMETRY  J  0.1397  0.37  1.0  0.0  
PERF      GEOA  'PRODUTOR 5'
** UBA              ff          Status  Connection  
  5 352 1           -  OPEN    FLOW-TO  'SURFACE'
  5 352 2           -  OPEN    FLOW-TO  1
  5 352 3           -  OPEN    FLOW-TO  2
  5 352 4           -  OPEN    FLOW-TO  3
  5 352 5           -  OPEN    FLOW-TO  4
  5 352 6           -  OPEN    FLOW-TO  5
  5 352 7           -  OPEN    FLOW-TO  6
  5 352 8           -  OPEN    FLOW-TO  7
  5 352 9           -  OPEN    FLOW-TO  8
  5 352 10           -  OPEN    FLOW-TO  9
  5 352 11           -  OPEN    FLOW-TO  10
  5 352 12           -  OPEN    FLOW-TO  11
  5 352 13           -  OPEN    FLOW-TO  12
  5 352 14           -  OPEN    FLOW-TO  13
  5 352 15           -  OPEN    FLOW-TO  14
  5 352 16           -  OPEN    FLOW-TO  15
  5 352 17           -  OPEN    FLOW-TO  16


WELL  'PRODUTOR 6'
PRODUCER 'PRODUTOR 6'
OPERATE  MIN  BHP  101.325  CONT 
**               rad      geofac    wfrac   skin
GEOMETRY  J  0.1397  0.37  1.0  0.0  
PERF      GEOA  'PRODUTOR 6'
** UBA              ff          Status  Connection  
  6 352 1           -  OPEN    FLOW-TO  'SURFACE'
  6 352 2           -  OPEN    FLOW-TO  1
  6 352 3           -  OPEN    FLOW-TO  2
  6 352 4           -  OPEN    FLOW-TO  3
  6 352 5           -  OPEN    FLOW-TO  4
  6 352 6           -  OPEN    FLOW-TO  5
  6 352 7           -  OPEN    FLOW-TO  6
  6 352 8           -  OPEN    FLOW-TO  7
  6 352 9           -  OPEN    FLOW-TO  8
  6 352 10           -  OPEN    FLOW-TO  9
  6 352 11           -  OPEN    FLOW-TO  10
  6 352 12           -  OPEN    FLOW-TO  11
  6 352 13           -  OPEN    FLOW-TO  12
  6 352 14           -  OPEN    FLOW-TO  13
  6 352 15           -  OPEN    FLOW-TO  14
  6 352 16           -  OPEN    FLOW-TO  15
  6 352 17           -  OPEN    FLOW-TO  16


WELL  'PRODUTOR 7'
PRODUCER 'PRODUTOR 7'
OPERATE  MIN  BHP  101.325  CONT 
**               rad      geofac    wfrac   skin
GEOMETRY  J  0.1397  0.37  1.0  0.0  
PERF      GEOA  'PRODUTOR 7'
** UBA              ff          Status  Connection  
  7 352 1           -  OPEN    FLOW-TO  'SURFACE'
  7 352 2           -  OPEN    FLOW-TO  1
  7 352 3           -  OPEN    FLOW-TO  2
  7 352 4           -  OPEN    FLOW-TO  3
  7 352 5           -  OPEN    FLOW-TO  4
  7 352 6           -  OPEN    FLOW-TO  5
  7 352 7           -  OPEN    FLOW-TO  6
  7 352 8           -  OPEN    FLOW-TO  7
  7 352 9           -  OPEN    FLOW-TO  8
  7 352 10           -  OPEN    FLOW-TO  9
  7 352 11           -  OPEN    FLOW-TO  10
  7 352 12           -  OPEN    FLOW-TO  11
  7 352 13           -  OPEN    FLOW-TO  12
  7 352 14           -  OPEN    FLOW-TO  13
  7 352 15           -  OPEN    FLOW-TO  14
  7 352 16           -  OPEN    FLOW-TO  15
  7 352 17           -  OPEN    FLOW-TO  16


WELL  'PRODUTOR 8'
PRODUCER 'PRODUTOR 8'
OPERATE  MIN  BHP  101.325  CONT 
**               rad      geofac    wfrac   skin
GEOMETRY  J  0.1397  0.37  1.0  0.0  
PERF      GEOA  'PRODUTOR 8'
** UBA              ff          Status  Connection  
  8 352 1           -  OPEN    FLOW-TO  'SURFACE'
  8 352 2           -  OPEN    FLOW-TO  1
  8 352 3           -  OPEN    FLOW-TO  2
  8 352 4           -  OPEN    FLOW-TO  3
  8 352 5           -  OPEN    FLOW-TO  4
  8 352 6           -  OPEN    FLOW-TO  5
  8 352 7           -  OPEN    FLOW-TO  6
  8 352 8           -  OPEN    FLOW-TO  7
  8 352 9           -  OPEN    FLOW-TO  8
  8 352 10           -  OPEN    FLOW-TO  9
  8 352 11           -  OPEN    FLOW-TO  10
  8 352 12           -  OPEN    FLOW-TO  11
  8 352 13           -  OPEN    FLOW-TO  12
  8 352 14           -  OPEN    FLOW-TO  13
  8 352 15           -  OPEN    FLOW-TO  14
  8 352 16           -  OPEN    FLOW-TO  15
  8 352 17           -  OPEN    FLOW-TO  16


WELL  'PRODUTOR 9'
PRODUCER 'PRODUTOR 9'
OPERATE  MIN  BHP  101.325  CONT 
**               rad      geofac    wfrac   skin
GEOMETRY  J  0.1397  0.37  1.0  0.0  
PERF      GEOA  'PRODUTOR 9'
** UBA              ff          Status  Connection  
  9 352 1           -  OPEN    FLOW-TO  'SURFACE'
  9 352 2           -  OPEN    FLOW-TO  1
  9 352 3           -  OPEN    FLOW-TO  2
  9 352 4           -  OPEN    FLOW-TO  3
  9 352 5           -  OPEN    FLOW-TO  4
  9 352 6           -  OPEN    FLOW-TO  5
  9 352 7           -  OPEN    FLOW-TO  6
  9 352 8           -  OPEN    FLOW-TO  7
  9 352 9           -  OPEN    FLOW-TO  8
  9 352 10           -  OPEN    FLOW-TO  9
  9 352 11           -  OPEN    FLOW-TO  10
  9 352 12           -  OPEN    FLOW-TO  11
  9 352 13           -  OPEN    FLOW-TO  12
  9 352 14           -  OPEN    FLOW-TO  13
  9 352 15           -  OPEN    FLOW-TO  14
  9 352 16           -  OPEN    FLOW-TO  15
  9 352 17           -  OPEN    FLOW-TO  16


WELL  'PRODUTOR 10'
PRODUCER 'PRODUTOR 10'
OPERATE  MIN  BHP  101.325  CONT 
**               rad      geofac    wfrac   skin
GEOMETRY  J  0.1397  0.37  1.0  0.0  
PERF      GEOA  'PRODUTOR 10'
** UBA              ff          Status  Connection  
  10 352 1           -  OPEN    FLOW-TO  'SURFACE'
  10 352 2           -  OPEN    FLOW-TO  1
  10 352 3           -  OPEN    FLOW-TO  2
  10 352 4           -  OPEN    FLOW-TO  3
  10 352 5           -  OPEN    FLOW-TO  4
  10 352 6           -  OPEN    FLOW-TO  5
  10 352 7           -  OPEN    FLOW-TO  6
  10 352 8           -  OPEN    FLOW-TO  7
  10 352 9           -  OPEN    FLOW-TO  8
  10 352 10           -  OPEN    FLOW-TO  9
  10 352 11           -  OPEN    FLOW-TO  10
  10 352 12           -  OPEN    FLOW-TO  11
  10 352 13           -  OPEN    FLOW-TO  12
  10 352 14           -  OPEN    FLOW-TO  13
  10 352 15           -  OPEN    FLOW-TO  14
  10 352 16           -  OPEN    FLOW-TO  15
  10 352 17           -  OPEN    FLOW-TO  16


WELL  'PRODUTOR 11'
PRODUCER 'PRODUTOR 11'
OPERATE  MIN  BHP  101.325  CONT 
**               rad      geofac    wfrac   skin
GEOMETRY  J  0.1397  0.37  1.0  0.0  
PERF      GEOA  'PRODUTOR 11'
** UBA              ff          Status  Connection  
  11 352 1           -  OPEN    FLOW-TO  'SURFACE'
  11 352 2           -  OPEN    FLOW-TO  1
  11 352 3           -  OPEN    FLOW-TO  2
  11 352 4           -  OPEN    FLOW-TO  3
  11 352 5           -  OPEN    FLOW-TO  4
  11 352 6           -  OPEN    FLOW-TO  5
  11 352 7           -  OPEN    FLOW-TO  6
  11 352 8           -  OPEN    FLOW-TO  7
  11 352 9           -  OPEN    FLOW-TO  8
  11 352 10           -  OPEN    FLOW-TO  9
  11 352 11           -  OPEN    FLOW-TO  10
  11 352 12           -  OPEN    FLOW-TO  11
  11 352 13           -  OPEN    FLOW-TO  12
  11 352 14           -  OPEN    FLOW-TO  13
  11 352 15           -  OPEN    FLOW-TO  14
  11 352 16           -  OPEN    FLOW-TO  15
  11 352 17           -  OPEN    FLOW-TO  16


WELL  'PRODUTOR 12'
PRODUCER 'PRODUTOR 12'
OPERATE  MIN  BHP  101.325  CONT 
**               rad      geofac    wfrac   skin
GEOMETRY  J  0.1397  0.37  1.0  0.0  
PERF      GEOA  'PRODUTOR 12'
** UBA              ff          Status  Connection  
  12 352 1           -  OPEN    FLOW-TO  'SURFACE'
  12 352 2           -  OPEN    FLOW-TO  1
  12 352 3           -  OPEN    FLOW-TO  2
  12 352 4           -  OPEN    FLOW-TO  3
  12 352 5           -  OPEN    FLOW-TO  4
  12 352 6           -  OPEN    FLOW-TO  5
  12 352 7           -  OPEN    FLOW-TO  6
  12 352 8           -  OPEN    FLOW-TO  7
  12 352 9           -  OPEN    FLOW-TO  8
  12 352 10           -  OPEN    FLOW-TO  9
  12 352 11           -  OPEN    FLOW-TO  10
  12 352 12           -  OPEN    FLOW-TO  11
  12 352 13           -  OPEN    FLOW-TO  12
  12 352 14           -  OPEN    FLOW-TO  13
  12 352 15           -  OPEN    FLOW-TO  14
  12 352 16           -  OPEN    FLOW-TO  15
  12 352 17           -  OPEN    FLOW-TO  16


WELL  'PRODUTOR 13'
PRODUCER 'PRODUTOR 13'
OPERATE  MIN  BHP  101.325  CONT 
**               rad      geofac    wfrac   skin
GEOMETRY  J  0.1397  0.37  1.0  0.0  
PERF      GEOA  'PRODUTOR 13'
** UBA              ff          Status  Connection  
  13 352 1           -  OPEN    FLOW-TO  'SURFACE'
  13 352 2           -  OPEN    FLOW-TO  1
  13 352 3           -  OPEN    FLOW-TO  2
  13 352 4           -  OPEN    FLOW-TO  3
  13 352 5           -  OPEN    FLOW-TO  4
  13 352 6           -  OPEN    FLOW-TO  5
  13 352 7           -  OPEN    FLOW-TO  6
  13 352 8           -  OPEN    FLOW-TO  7
  13 352 9           -  OPEN    FLOW-TO  8
  13 352 10           -  OPEN    FLOW-TO  9
  13 352 11           -  OPEN    FLOW-TO  10
  13 352 12           -  OPEN    FLOW-TO  11
  13 352 13           -  OPEN    FLOW-TO  12
  13 352 14           -  OPEN    FLOW-TO  13
  13 352 15           -  OPEN    FLOW-TO  14
  13 352 16           -  OPEN    FLOW-TO  15
  13 352 17           -  OPEN    FLOW-TO  16


WELL  'PRODUTOR 14'
PRODUCER 'PRODUTOR 14'
OPERATE  MIN  BHP  101.325  CONT 
**               rad      geofac    wfrac   skin
GEOMETRY  J  0.1397  0.37  1.0  0.0  
PERF      GEOA  'PRODUTOR 14'
** UBA              ff          Status  Connection  
  14 352 1           -  OPEN    FLOW-TO  'SURFACE'
  14 352 2           -  OPEN    FLOW-TO  1
  14 352 3           -  OPEN    FLOW-TO  2
  14 352 4           -  OPEN    FLOW-TO  3
  14 352 5           -  OPEN    FLOW-TO  4
  14 352 6           -  OPEN    FLOW-TO  5
  14 352 7           -  OPEN    FLOW-TO  6
  14 352 8           -  OPEN    FLOW-TO  7
  14 352 9           -  OPEN    FLOW-TO  8
  14 352 10           -  OPEN    FLOW-TO  9
  14 352 11           -  OPEN    FLOW-TO  10
  14 352 12           -  OPEN    FLOW-TO  11
  14 352 13           -  OPEN    FLOW-TO  12
  14 352 14           -  OPEN    FLOW-TO  13
  14 352 15           -  OPEN    FLOW-TO  14
  14 352 16           -  OPEN    FLOW-TO  15
  14 352 17           -  OPEN    FLOW-TO  16


WELL  'PRODUTOR 15'
PRODUCER 'PRODUTOR 15'
OPERATE  MIN  BHP  101.325  CONT 
**               rad      geofac    wfrac   skin
GEOMETRY  J  0.1397  0.37  1.0  0.0  
PERF      GEOA  'PRODUTOR 15'
** UBA              ff          Status  Connection  
  15 352 1           -  OPEN    FLOW-TO  'SURFACE'
  15 352 2           -  OPEN    FLOW-TO  1
  15 352 3           -  OPEN    FLOW-TO  2
  15 352 4           -  OPEN    FLOW-TO  3
  15 352 5           -  OPEN    FLOW-TO  4
  15 352 6           -  OPEN    FLOW-TO  5
  15 352 7           -  OPEN    FLOW-TO  6
  15 352 8           -  OPEN    FLOW-TO  7
  15 352 9           -  OPEN    FLOW-TO  8
  15 352 10           -  OPEN    FLOW-TO  9
  15 352 11           -  OPEN    FLOW-TO  10
  15 352 12           -  OPEN    FLOW-TO  11
  15 352 13           -  OPEN    FLOW-TO  12
  15 352 14           -  OPEN    FLOW-TO  13
  15 352 15           -  OPEN    FLOW-TO  14
  15 352 16           -  OPEN    FLOW-TO  15
  15 352 17           -  OPEN    FLOW-TO  16


WELL  'PRODUTOR 16'
PRODUCER 'PRODUTOR 16'
OPERATE  MIN  BHP  101.325  CONT 
**               rad      geofac    wfrac   skin
GEOMETRY  J  0.1397  0.37  1.0  0.0  
PERF      GEOA  'PRODUTOR 16'
** UBA              ff          Status  Connection  
  16 352 1           -  OPEN    FLOW-TO  'SURFACE'
  16 352 2           -  OPEN    FLOW-TO  1
  16 352 3           -  OPEN    FLOW-TO  2
  16 352 4           -  OPEN    FLOW-TO  3
  16 352 5           -  OPEN    FLOW-TO  4
  16 352 6           -  OPEN    FLOW-TO  5
  16 352 7           -  OPEN    FLOW-TO  6
  16 352 8           -  OPEN    FLOW-TO  7
  16 352 9           -  OPEN    FLOW-TO  8
  16 352 10           -  OPEN    FLOW-TO  9
  16 352 11           -  OPEN    FLOW-TO  10
  16 352 12           -  OPEN    FLOW-TO  11
  16 352 13           -  OPEN    FLOW-TO  12
  16 352 14           -  OPEN    FLOW-TO  13
  16 352 15           -  OPEN    FLOW-TO  14
  16 352 16           -  OPEN    FLOW-TO  15
  16 352 17           -  OPEN    FLOW-TO  16


WELL  'PRODUTOR 17'
PRODUCER 'PRODUTOR 17'
OPERATE  MIN  BHP  101.325  CONT 
**               rad      geofac    wfrac   skin
GEOMETRY  J  0.1397  0.37  1.0  0.0  
PERF      GEOA  'PRODUTOR 17'
** UBA              ff          Status  Connection  
  17 352 1           -  OPEN    FLOW-TO  'SURFACE'
  17 352 2           -  OPEN    FLOW-TO  1
  17 352 3           -  OPEN    FLOW-TO  2
  17 352 4           -  OPEN    FLOW-TO  3
  17 352 5           -  OPEN    FLOW-TO  4
  17 352 6           -  OPEN    FLOW-TO  5
  17 352 7           -  OPEN    FLOW-TO  6
  17 352 8           -  OPEN    FLOW-TO  7
  17 352 9           -  OPEN    FLOW-TO  8
  17 352 10           -  OPEN    FLOW-TO  9
  17 352 11           -  OPEN    FLOW-TO  10
  17 352 12           -  OPEN    FLOW-TO  11
  17 352 13           -  OPEN    FLOW-TO  12
  17 352 14           -  OPEN    FLOW-TO  13
  17 352 15           -  OPEN    FLOW-TO  14
  17 352 16           -  OPEN    FLOW-TO  15
  17 352 17           -  OPEN    FLOW-TO  16


